lcgcmt_installarea=without_installarea
CMTPATH=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1:/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1:/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1:/afs/cern.ch/lhcb/software/releases/DBASE:/afs/cern.ch/lhcb/software/releases/PARAM:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
CMT_tag=$(tag)
CMTROOT=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520
CMT_root=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520
CMTVERSION=v1r20p20090520
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/InstallArea/x86_64-slc6-gcc48-opt/scripts:/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/InstallArea/x86_64-slc6-gcc48-opt/scripts:/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/InstallArea/x86_64-slc6-gcc48-opt/scripts:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/InstallArea/x86_64-slc6-gcc48-opt/scripts:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/InstallArea/x86_64-slc6-gcc48-opt/scripts:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/InstallArea/x86_64-slc6-gcc48-opt/scripts:/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/pytools/1.9_python2.7/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/mysql/5.5.30/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/pyanalysis/1.5_python2.7/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/XercesC/3.1.1p1/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/vdt/0.3.6/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/tbb/42_20140122/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/ROOT/6.06.02/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/xrootd/4.2.3/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/Python/2.7.10/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/gcc/4.8.4/x86_64-slc6/bin:/afs/cern.ch/sw/contrib/CMT/v1r20p20090520/${CMTBIN}:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/gperftools/2.4.91/x86_64-slc6-gcc48-opt/bin:/usr/lib64/qt-3.3/bin:/usr/bin:/usr/externals/bin:/usr/sbin:/usr/local/openssh/pro/bin:/afs/cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v8r6p1/InstallArea/scripts:/afs/cern.ch/lhcb/software/releases/COMPAT/COMPAT_v1r19/CompatSys/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/lhcb/bin:/afs/cern.ch/sw/lcg/contrib/CMake/3.3.2/Linux-x86_64/bin:.:/etc/alternatives/java_sdk/bin:/usr/local/bin:/bin:/opt/lal/bin:/users/LHCb/abdulkhalek//bin:/usr/java/latest/bin
CLASSPATH=/afs/cern.ch/sw/contrib/CMT/v1r20p20090520/java
debug_option=-g
cc=$(cc_name)
cdebugflags=$(coptimized_s)
cflags= -std=c11 -fmessage-length=0 -fPIC 
pp_cflags= $(CppSpecificFlags) -DHAVE_GAUDI_PLUGINSVC 
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=$(cpp_name)
cppdebugflags=$(cppoptimized_s)
cppflags= -fmessage-length=0 -Df2cFortran -fPIC -D_GNU_SOURCE -Dlinux -Dunix -pipe -Wall -Wextra -Werror=return-type -pthread -pedantic -Wno-long-long  -std=c++11 -Wno-deprecated -Wno-unused-local-typedefs -std=c++11  -O3 -ftree-vectorize 
pp_cppflags=-D_GNU_SOURCE -DGAUDI_V20_COMPAT  -DBOOST_FILESYSTEM_VERSION=3  -DBOOST_SPIRIT_USE_PHOENIX_V3  $(CppSpecificFlags) -DHAVE_GAUDI_PLUGINSVC 
cppcomp=$(cpp) -c $(cppdebugflags) $(cppflags) $(pp_cppflags) $(includes)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags) -ldl -Wl,--as-needed -Wl,--no-undefined 
cpplink=$(cpp) $(cpplinkflags)
for=$(for_name)
fflags=-fmessage-length=0 -O2 -fdollar-ok -w -fPIC
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=$(cpp_name) $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=lockfile 
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=/usr/bin/python ${CMTROOT}/mgr/cmt_svn_checkout.py 
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo --log=./install.$(tag).history 
uninstall_command=python $(GaudiPolicy_root)/scripts/install.py -u --log=./install.$(tag).history 
cmt_installarea_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-sl67-gcc484
PrKernel_tag=$(tag)
PRKERNELROOT=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/Pr/PrKernel
PrKernel_root=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/Pr/PrKernel
PRKERNELVERSION=v1r10
PrKernel_cmtpath=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1
PrKernel_offset=Pr
PrKernel_project=Brunel_v50r1
RecEvent_tag=$(tag)
RECEVENTROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Event/RecEvent
RecEvent_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Event/RecEvent
RECEVENTVERSION=v2r57
RecEvent_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
RecEvent_offset=Event
RecEvent_project=LHCB
RecEvent_project_release=LHCB_v40r1
EventBase_tag=$(tag)
EVENTBASEROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Event/EventBase
EventBase_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Event/EventBase
EVENTBASEVERSION=v3r1
EventBase_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
EventBase_offset=Event
EventBase_project=LHCB
EventBase_project_release=LHCB_v40r1
LHCbKernel_tag=$(tag)
LHCBKERNELROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Kernel/LHCbKernel
LHCbKernel_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Kernel/LHCbKernel
LHCBKERNELVERSION=v16r1
LHCbKernel_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
LHCbKernel_offset=Kernel
LHCbKernel_project=LHCB
LHCbKernel_project_release=LHCB_v40r1
LHCbMath_tag=$(tag)
LHCBMATHROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Kernel/LHCbMath
LHCbMath_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Kernel/LHCbMath
LHCBMATHVERSION=v3r62
LHCbMath_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
LHCbMath_offset=Kernel
LHCbMath_project=LHCB
LHCbMath_project_release=LHCB_v40r1
GaudiKernel_tag=$(tag)
GAUDIKERNELROOT=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiKernel
GaudiKernel_root=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiKernel
GAUDIKERNELVERSION=v33r1
GaudiKernel_cmtpath=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1
GaudiKernel_project=GAUDI
GaudiKernel_project_release=GAUDI_v27r1
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiPolicy
GaudiPolicy_root=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiPolicy
GAUDIPOLICYVERSION=v15r8
GaudiPolicy_cmtpath=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=GAUDI_v27r1
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings
LCG_Settings_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_84
LCG_releases=$(LCG_Settings_root)/../../../LCG_84
LCG_external=$(LCG_Settings_root)/../../../LCG_84
unixdirname=lib64
gcc_config_version=4.8.4
gcc_native_version=$(gcc_config_version)
gcc_home=$(LCG_external)/gcc/$(gcc_native_version)/$(LCG_hostos)
clang_native_version=$(clang_config_version)
clang_home=$(LCG_base)/llvm/$(clang_native_version)/$(LCG_hostos)
icc_native_version=$(icc_config_version)
cc_name=lcg-gcc-$(gcc_config_version)
cpp_name=lcg-g++-$(gcc_config_version)
cpplinkname=$(cpp_name)
for_name=lcg-gfortran-$(gcc_config_version)
COMPILER_PATH=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/gcc/4.8.4/x86_64-slc6/lib/gcc/x86_64-unknown-linux-gnu/4.8.4
LD_LIBRARY_PATH=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/pytools/1.9_python2.7/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/mysql/5.5.30/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/pyanalysis/1.5_python2.7/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/lapack/3.5.0/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/blas/20110419/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/clhep/2.3.1.1/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/XercesC/3.1.1p1/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/vdt/0.3.6/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/GSL/1.10/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/tbb/42_20140122/x86_64-slc6-gcc48-opt/bin:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/Boost/1.59.0_python2.7/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/ROOT/6.06.02/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/xrootd/4.2.3/x86_64-slc6-gcc48-opt/lib64:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/libunwind/5c2cade/x86_64-slc6-gcc48-opt/lib:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/gcc/4.8.4/x86_64-slc6/lib64:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/gperftools/2.4.91/x86_64-slc6-gcc48-opt/lib:/usr/lib64/classads:/usr/lib64:/usr/lib:.:/exp/LHCb/software/lhcb/lib4fix:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/Python/2.7.10/x86_64-slc6-gcc48-opt/lib
Python_tag=$(tag)
PYTHONROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/Python
Python_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_84
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Configuration
LCG_Configuration_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Configuration
LCG_CONFIGURATIONVERSION=v1
LCG_Configuration_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_84
LCG_Platforms_tag=$(tag)
LCG_PLATFORMSROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Platforms
LCG_Platforms_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Platforms
LCG_PLATFORMSVERSION=v1
LCG_Platforms_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
LCG_Platforms_project=LCGCMT
LCG_Platforms_project_release=LCGCMT_84
LCG_arch=x86_64
LCG_os=slc6
LCG_compiler=gcc48
LCG_mode=opt
LCG_basesystem=$(LCG_arch)-$(LCG_os)-$(LCG_compiler)
LCG_system=$(LCG_basesystem)-$(LCG_mode)
LCG_platform=$(LCG_basesystem)-$(LCG_mode)
ATLAS_TAGS_MAP=none
host_compiler=gcc44
host_arch=x86_64
host_os=slc6
host_cmtconfig=x86_64-slc6-gcc44-opt
LCG_hostos=$(host_arch)-$(host_os)
LCG_hostarch=$(host_arch)
LCG_config_version=84
uuid_config_version=dummy
4suite_config_version=1.0.2p1
AIDA_config_version=3.2.1
Boost_config_version=1.59.0
Boost_file_version=1_59
CASTOR_config_version=2.1.13-6
CMake_config_version=3.4.1
COOL_config_version=3_1_3
CORAL_config_version=3_1_3
CLHEP_config_version=2.3.1.1
CppUnit_config_version=1.12.1_p1
Davix_config_version=0.4.0
Expat_config_version=2.0.1
FTS3_config_version=0.0.1-88
FTS_config_version=2.2.8emi2
Frontier_Client_config_version=2.8.18
GSL_config_version=1.10
Geant4_config_version=10.01.p02
HepMC_config_version=2.06.09
HepPDT_config_version=2.06.01
Jinja2_config_version=2.7.3
LCGCMT_config_version=LCGCMT_84
MarkupSafe_config_version=0.23
PyYAML_config_version=3.11
Python_config_version=2.7.10
Python_config_version_twodigit=2.7
QMtest_config_version=2.4.1
Qt5_config_version=5.4.1
Qt_config_version=4.8.4
RELAX_config_version=RELAX-root6
ROOT_config_version=6.06.02
WMS_config_version=3.4.0
XercesC_config_version=3.1.1p1
astroid_config_version=1.3.6
backports_config_version=3.4.0.2
blas_config_version=20110419
certifi_config_version=14.05.14
cmaketools_config_version=1.1
cmt_config_version=v1r20p20090520
coin3d_config_version=3.1.3p2
coverage_config_version=3.5.2
cream_config_version=1.14.0-4
cx_oracle_config_version=5.1.1
dcap_config_version=2.47.7-1
dm-util_config_version=1.15.0-0
doxygen_config_version=1.8.9.1
dpm_config_version=1.8.5-1
eigen_config_version=3.2.7
epel_config_version=20130408
fastjet_config_version=3.1.1
fftw_config_version=3.1.2
genshi_config_version=0.6
gfal2_config_version=2.2.0-1
gfal_config_version=1.13.0-0
gmp_config_version=6.0.0
gperftools_config_version=2.4.91
graphviz_config_version=2.28.0
gridftp_ifce_config_version=2.3.1-0
gridsite_config_version=1.7.25-1.emi2
gtest_config_version=master20160308
hepmc3_config_version=githead
igprof_config_version=5.9.11
ipython_config_version=4.0.1
is_ifce_config_version=1.15.0-0
jemalloc_config_version=4.1.0
json_config_version=2.5.2
jsonschema_config_version=2.4.0
jupyter_config_version=1.0.0
lapack_config_version=3.5.0
lb_config_version=3.2.9
lcgdmcommon_config_version=1.8.5-1
lcgenv_config_version=1.3.2.1
lcginfosites_config_version=3.1.0-3
lcov_config_version=1.9
lfc_config_version=1.8.5-1
libsvm_config_version=2.86
libtool_config_version=2.4.2
libunwind_config_version=5c2cade
libxml2_config_version=2.9.3
libxslt_config_version=1.1.28
logilabcommon_config_version=1.0.1
lxml_config_version=2.3
matplotlib_config_version=1.4.3
messaging_config_version=1.0
metakernel_config_version=0.11.8
mistune_config_version=0.5.1
mock_config_version=0.8.0
mpich2_config_version=1.5
multiprocessing_config_version=2.6.2.1
mysql_config_version=5.5.30
mysql_python_config_version=1.2.3
neurobayes_config_version=3.7.0
neurobayes_expert_config_version=3.7.0
ninja_config_version=1.6.0
nose_config_version=1.1.2
numexpr_config_version=2.4.3
numpy_config_version=1.9.2
oracle_config_version=11.2.0.3.0
pacparser_config_version=1.3.5
pandas_config_version=0.16.1
pathos_config_version=0.2a.dev-20120503
pcre_config_version=8.38
pip_config_version=7.1.2
prettytable_config_version=0.7.2
processing_config_version=0.52
ptyprocess_config_version=0.4
py2neo_config_version=1.4.6
py_config_version=1.4.8
pyanalysis_config_version=1.5
pydot_config_version=1.0.28
pygments_config_version=2.0.2
pygraphics_config_version=1.5
pygsi_config_version=0.6.3
pyminuit_config_version=0.0.1
pyparsing_config_version=2.0.3
pyqt_config_version=4.9.5
pytest_config_version=2.2.4
python_dateutil_config_version=2.4.0
pytools_config_version=1.9
pytz_config_version=2015.4
pyxml_config_version=0.8.4p1
pyzmq_config_version=14.5.0
qwt_config_version=6.0.1
scikitlearn_config_version=0.16.1
scipy_config_version=0.15.1
setuptools_config_version=20.1.1
sip_config_version=4.14
six_config_version=1.9.0
soqt_config_version=1.5.0
sqlalchemy_config_version=0.7.7
sqlite_config_version=3110100
srm_ifce_config_version=1.13.0-0
stomppy_config_version=3.1.3
storm_config_version=0.19
subprocess32_config_version=3.2.6
swig_config_version=2.0.11
sympy_config_version=0.7.6
tbb_config_version=42_20140122
terminado_config_version=0.5
tornado_config_version=4.0.2
valgrind_config_version=3.11.0
vdt_config_version=0.3.6
vectorclass_config_version=1.16
voms_config_version=2.0.9-1
xapian_config_version=1.2.21
xqilla_config_version=2.2.4p1
xrootd_config_version=4.2.3
xrootd_python_config_version=0.3.0
yamlcpp_config_version=0.5.1
Python_native_version=$(Python_config_version)
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_version=$(Python_config_version_twodigit)
Python_libversion_cmd=python -c "print ''.join('$(Python_config_version)'.split('.')[:2])"
Python_libversion=$(Python_config_version_twodigit)
Python_include=$(Python_inc)
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_libversion) -lutil -lpthread 
Python_export_paths=$(Python_home)
MANPATH=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/mysql/5.5.30/x86_64-slc6-gcc48-opt/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/pyanalysis/1.5_python2.7/x86_64-slc6-gcc48-opt/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/GSL/1.10/x86_64-slc6-gcc48-opt/share/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/ROOT/6.06.02/x86_64-slc6-gcc48-opt/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/libunwind/5c2cade/x86_64-slc6-gcc48-opt/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/Python/2.7.10/x86_64-slc6-gcc48-opt/share/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/gperftools/2.4.91/x86_64-slc6-gcc48-opt/share/man:/usr/man:/usr/share/man:/usr/local/share/man:/usr/local/subversion/pro/man:/usr/local/cvs/pro/man:/usr/local/bbftp/pro/man:/usr/local/man:/lal_prod/common/gen/man:/usr/X11R6/man:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/ROOT/6.06.02/src/root/man
ROOT_INCLUDE_PATH=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/InstallArea/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/InstallArea/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/InstallArea/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/InstallArea/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/InstallArea/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/InstallArea/x86_64-slc6-gcc48-opt/include:.:.:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/mysql/5.5.30/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/clhep/2.3.1.1/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/XercesC/3.1.1p1/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/AIDA/3.2.1/x86_64-slc6-gcc48-opt/src/cpp:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/eigen/3.2.7/x86_64-slc6-gcc48-opt/include/eigen3:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/vdt/0.3.6/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/GSL/1.10/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/tbb/42_20140122/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/Boost/1.59.0_python2.7/x86_64-slc6-gcc48-opt/include/boost-1_59:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/xrootd/4.2.3/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/gperftools/2.4.91/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/libunwind/5c2cade/x86_64-slc6-gcc48-opt/include:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/Python/2.7.10/x86_64-slc6-gcc48-opt/include/python2.7
tcmalloc_tag=$(tag)
TCMALLOCROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/tcmalloc
tcmalloc_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/tcmalloc
TCMALLOCVERSION=v1
tcmalloc_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
tcmalloc_offset=LCG_Interfaces
tcmalloc_project=LCGCMT
tcmalloc_project_release=LCGCMT_84
libunwind_tag=$(tag)
LIBUNWINDROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/libunwind
libunwind_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/libunwind
LIBUNWINDVERSION=v1
libunwind_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
libunwind_offset=LCG_Interfaces
libunwind_project=LCGCMT
libunwind_project_release=LCGCMT_84
libunwind_native_version=$(libunwind_config_version)
libunwind_home=$(LCG_external)/libunwind/$(libunwind_native_version)/$(LCG_system)
libunwind_include=$(libunwind_home)/include
libunwind_linkopts=-L$(libunwind_home)/lib -lunwind -lunwind-x86_64
libunwind_cppflags=-I $(libunwind_home)/include
libunwind_export_paths= $(libunwind_home)/include $(libunwind_home)/lib 
tcmalloc_native_version=$(gperftools_config_version)
tcmalloc_home=$(LCG_external)/gperftools/$(tcmalloc_native_version)/$(LCG_system)
tcmalloc_include=$(tcmalloc_home)/include
copyInclude=cp -Rup 
python_bin_module_dir=$(tag)/python/lib-dynload
cmt_actions_constituents=       
cmt_actions_constituentsclean= new_rootsysclean TestProjectclean TestPackageclean qmtest_summarizeclean qmtest_runclean makeclean 
remove_command=$(cmt_uninstallarea_command)
dq="
BINDIR=$(tag)
cpp_fragment=cpp
cpp_library_fragment=cpp_library
vsDebug=2
merge_componentslist_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
merge_rootmap_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
libdirname=lib
bindirname=bin
cppdebugflags_s=-Og -g
cppoptimized_s=-O2 -DNDEBUG
cppprofiled_s=-pg
cdebugflags_s=-Og -g
coptimized_s=-O2 -DNDEBUG
fdebugflags= $(foptimized_s)
fdebugflags_s=-Og -g
foptimized_s=-O2 -DNDEBUG
fprofiled_s=-pg
GaudiKernel_linkopts= -lGaudiKernel 
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000 
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000 
application_linkopts=-Wl,--export-dynamic 
shared_install_subdir=/$(tag)
genconfDir=$(shared_install_subdir)/genConf/
merge_genconfDb_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
genconfig_configurableModuleName=GaudiKernel.Proxy
genconfig_configurableDefaultName=Configurable.DefaultName
genconfig_configurableAlgorithm=ConfigurableAlgorithm
genconfig_configurableAlgTool=ConfigurableAlgTool
genconfig_configurableAuditor=ConfigurableAuditor
genconfig_configurableService=ConfigurableService
use_GaudiCoreSvc=GaudiCoreSvc * -no_auto_imports
strip_script=$(GAUDIPOLICYROOT)/scripts/StripPath
GenConfUser_script=genconfuser.py
Reflex_tag=$(tag)
REFLEXROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/Reflex
Reflex_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_84
ROOT_tag=$(tag)
ROOTROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/ROOT
ROOT_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_84
xrootd_tag=$(tag)
XROOTDROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/xrootd
xrootd_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/xrootd
XROOTDVERSION=v1
xrootd_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
xrootd_offset=LCG_Interfaces
xrootd_project=LCGCMT
xrootd_project_release=LCGCMT_84
xrootd_native_version=$(xrootd_config_version)
xrootd_home=$(LCG_external)/xrootd/$(xrootd_native_version)/$(LCG_system)
xrootd_include=$(xrootd_home)/include
xrootd_linkopts=-L$(xrootd_home)/$(unixdirname) 
xrootd_export_paths= $(xrootd_home)/bin $(xrootd_home)/include $(xrootd_home)/$(unixdirname)   $(xrootd_home)/share
ROOT_native_version=$(ROOT_config_version)
ROOT_base=$(LCG_releases)/ROOT/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)
ROOT_linkopts=-L$(ROOT_home)/lib -lCore -lTree -lpthread  -lRIO -lMathCore -lGenVector  -lMathCore -lGenVector -lHist -lXMLIO 
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lCore 
ROOTSYS=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/ROOT/6.06.02/x86_64-slc6-gcc48-opt
ROOT_name=root
ROOT_header_file_filter=$(ROOT_home)/include
ROOT_header_file_stamp=$(ROOT_home)/include/Type.h
PYTHONPATH=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/InstallArea/x86_64-slc6-gcc48-opt/python/lib-dynload:/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/InstallArea/x86_64-slc6-gcc48-opt/python.zip:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/pytools/1.9_python2.7/x86_64-slc6-gcc48-opt/lib/python2.7/site-packages:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/pyanalysis/1.5_python2.7/x86_64-slc6-gcc48-opt/lib/python2.7/site-packages:/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/ROOT/6.06.02/x86_64-slc6-gcc48-opt/lib:/usr/lib64/python:/afs/cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v8r6p1/InstallArea/python
rootcint="$(ROOT_home)/bin/rootcint"
genmap_cmd=$(ROOTSYS)/bin/genmap
ROOT_export_paths= $(ROOT_home) 
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
gccxmloptsval=--gccxml-compiler $(cpp_name) 
gccxmlopts=--gccxmlopt='$(gccxmloptsval)'
COOLVERS=3_1_3
CORALVERS=3_1_3
ROOTVERS=6.06.02
BoostVERS=1.59.0
uuidVERS=dummy
GCCXMLVERS=${GCCXML_config_version}
AIDAVERS=3.2.1
XercesCVERS=3.1.1p1
GSLVERS=1.10
PythonVERS=2.7.10
HepMCVERS=2.06.09
QMtestVERS=2.4.1
LCGCMTVERS=84
GAUDI_DOXY_HOME=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiRelease/doc
GaudiPluginService_tag=$(tag)
GAUDIPLUGINSERVICEROOT=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiPluginService
GaudiPluginService_root=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiPluginService
GAUDIPLUGINSERVICEVERSION=v3r1
GaudiPluginService_cmtpath=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1
GaudiPluginService_project=GAUDI
GaudiPluginService_project_release=GAUDI_v27r1
includes= $(ppcmd)"$(PrKernel_root)"  $(ppcmd)"/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/InstallArea/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/InstallArea/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/InstallArea/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/InstallArea/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/InstallArea/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/InstallArea/x86_64-slc6-gcc48-opt/include" $(use_includes)
GaudiPluginService_linkopts= -lGaudiPluginService 
GaudiPluginService_stamps=${GAUDIPLUGINSERVICEROOT}/${BINDIR}/GaudiPluginService.stamp 
GaudiPluginService_linker_library=GaudiPluginService
zip_GaudiPluginService_python_modules_dependencies= GaudiPluginService_python_init 
GaudiPluginService_python_init_dependencies= GaudiPluginService_python 
listcomponents_dependencies= GaudiPluginService 
listcomponentslinkopts= -ldl 
listcomponents_cmd=listcomponents.exe
Boost_tag=$(tag)
BOOSTROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/Boost
Boost_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/Boost
BOOSTVERSION=v1
Boost_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
Boost_offset=LCG_Interfaces
Boost_project=LCGCMT
Boost_project_release=LCGCMT_84
Boost_native_version=$(Boost_config_version)_python$(Python_config_version_twodigit)
Boost_home=$(LCG_external)/Boost/$(Boost_native_version)/$(LCG_system)
Boost_include=$(Boost_home)/include/boost-$(Boost_file_version)
Boost_compiler_version=$(LCG_compiler)
Boost_linkopts=-L$(Boost_home)/lib  $(Boost_linkopts_system)  $(Boost_linkopts_regex) 
Boost_linkopts_python= -lboost_python-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_system= -lboost_system-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_filesystem= -lboost_filesystem-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_filesystem_mt= -lboost_filesystem-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_iostreams= -lboost_iostreams-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_regex= -lboost_regex-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_thread= -lboost_thread-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_program_options= -lboost_program_options-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_serialization= -lboost_serialization-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_date_time= -lboost_date_time-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_graph= -lboost_graph-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_header_file_filter=$(Boost_home)/include/boost-$(Boost_file_version)
Boost_header_file_stamp=$(Boost_home)/include/boost-$(Boost_file_version)/boost/any.hpp
Boost_export_paths=$(Boost_home)
tbb_tag=$(tag)
TBBROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/tbb
tbb_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/tbb
TBBVERSION=v1
tbb_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
tbb_offset=LCG_Interfaces
tbb_project=LCGCMT
tbb_project_release=LCGCMT_84
tbb_native_version=$(tbb_config_version)
tbb_home=$(LCG_external)/tbb/$(tbb_native_version)/$(LCG_system)
tbb_include=$(tbb_home)/include
tbb_linkopts=-L$(tbb_home)/lib -ltbb
tbb_export_paths= $(tbb_home)/include $(tbb_home)/lib 
GaudiKernel_stamps=${GAUDIKERNELROOT}/${BINDIR}/GaudiKernel.stamp 
GaudiKernel_linker_library=GaudiKernel
zip_GaudiKernel_python_modules_dependencies= GaudiKernel_python_init 
GaudiKernel_python_init_dependencies= GaudiKernel_python 
GaudiKernelDict_use_linkopts=$(use_linkopts)
GaudiKernelGen_dependencies=install_more_includes
genconfig_cmd=genconf.exe
VectorClass_tag=$(tag)
VECTORCLASSROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Kernel/VectorClass
VectorClass_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Kernel/VectorClass
VECTORCLASSVERSION=v1r19
VectorClass_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
VectorClass_offset=Kernel
VectorClass_project=LHCB
VectorClass_project_release=LHCB_v40r1
VectorClass_linkopts= -lVectorClassLib 
VectorClass_stamps=${VECTORCLASSROOT}/${BINDIR}/VectorClassLib.stamp 
VectorClass_linker_library=VectorClassLib
VectorClassLib_cppflags= -Wno-overflow -Wno-sign-compare -Wno-strict-aliasing 
GSL_tag=$(tag)
GSLROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/GSL
GSL_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/GSL
GSLVERSION=v1
GSL_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
GSL_offset=LCG_Interfaces
GSL_project=LCGCMT
GSL_project_release=LCGCMT_84
GSL_native_version=$(GSL_config_version)
GSL_home=$(LCG_external)/GSL/$(GSL_native_version)/$(LCG_system)
GSL_include=$(GSL_home)/include
GSL_linkopts=-L$(GSL_home)/lib -lgsl -lgslcblas 
GSL_export_paths=$(GSL_home)/lib $(GSL_home)/include
vdt_tag=$(tag)
VDTROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/vdt
vdt_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/vdt
VDTVERSION=v1
vdt_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
vdt_offset=LCG_Interfaces
vdt_project=LCGCMT
vdt_project_release=LCGCMT_84
vdt_native_version=$(vdt_config_version)
vdt_home=$(LCG_external)/vdt/$(vdt_native_version)/$(LCG_system)
vdt_linkopts= -L$(vdt_home)/lib -lvdt 
vdt_include=$(vdt_home)/include
eigen_tag=$(tag)
EIGENROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/eigen
eigen_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/eigen
EIGENVERSION=v1
eigen_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
eigen_offset=LCG_Interfaces
eigen_project=LCGCMT
eigen_project_release=LCGCMT_84
eigen_native_version=$(eigen_config_version)
eigen_home=$(LCG_external)/eigen/$(eigen_native_version)/$(LCG_system)
eigen_include=$(eigen_home)/include/eigen3
eigen_export_paths= $(eigen_home)/include/eigen3 
GaudiGSL_tag=$(tag)
GAUDIGSLROOT=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiGSL
GaudiGSL_root=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiGSL
GAUDIGSLVERSION=v9r2
GaudiGSL_cmtpath=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1
GaudiGSL_project=GAUDI
GaudiGSL_project_release=GAUDI_v27r1
GaudiAlg_tag=$(tag)
GAUDIALGROOT=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiAlg
GaudiAlg_root=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiAlg
GAUDIALGVERSION=v17r1
GaudiAlg_cmtpath=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1
GaudiAlg_project=GAUDI
GaudiAlg_project_release=GAUDI_v27r1
GaudiUtils_tag=$(tag)
GAUDIUTILSROOT=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiUtils
GaudiUtils_root=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiUtils
GAUDIUTILSVERSION=v6r2
GaudiUtils_cmtpath=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1
GaudiUtils_project=GAUDI
GaudiUtils_project_release=GAUDI_v27r1
AIDA_tag=$(tag)
AIDAROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/AIDA
AIDA_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/AIDA
AIDAVERSION=v1
AIDA_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
AIDA_offset=LCG_Interfaces
AIDA_project=LCGCMT
AIDA_project_release=LCGCMT_84
AIDA_native_version=$(AIDA_config_version)
AIDA_home=$(LCG_external)/AIDA/$(AIDA_native_version)/$(LCG_system)
AIDA_include=$(AIDA_home)/src/cpp
AIDA_export_paths=${AIDA_home}/src/cpp
uuid_tag=$(tag)
UUIDROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/uuid
uuid_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/uuid
UUIDVERSION=v1
uuid_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
uuid_offset=LCG_Interfaces
uuid_project=LCGCMT
uuid_project_release=LCGCMT_84
uuid_native_version=$(uuid_config_version)
uuid_home=/usr
uuid_includes=.
uuid_include=$(uuid_includes)
uuid_linkopts=-luuid
uuid_export_paths= 
XercesC_tag=$(tag)
XERCESCROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/XercesC
XercesC_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/XercesC
XERCESCVERSION=v1
XercesC_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
XercesC_offset=LCG_Interfaces
XercesC_project=LCGCMT
XercesC_project_release=LCGCMT_84
XercesC_native_version=$(XercesC_config_version)
XercesC_home=$(LCG_external)/XercesC/$(XercesC_native_version)/$(LCG_system)
XercesC_include=$(XercesC_home)/include
XercesC_linkopts=-L$(XercesC_home)/lib -lxerces-c -lpthread
XercesC_warnings=-w -Wno-unused
XercesC_cppflags= -DXERCESC_GE_31 
XercesC_export_paths= $(XercesC_home)/include $(XercesC_home)/lib
GaudiUtils_linkopts= -lGaudiUtilsLib 
GaudiUtils_stamps=${GAUDIUTILSROOT}/${BINDIR}/GaudiUtilsLib.stamp 
GaudiUtils_linker_library=GaudiUtilsLib
GaudiUtils_dependencies=$(GaudiUtils_linker_library) 
GaudiUtilsComponentsList_dependencies= GaudiUtils 
GaudiAlg_linkopts= -lGaudiAlgLib 
GaudiAlg_stamps=${GAUDIALGROOT}/${BINDIR}/GaudiAlgLib.stamp 
GaudiAlg_linker_library=GaudiAlgLib
GaudiAlg_dependencies=$(GaudiAlg_linker_library) 
GaudiAlgComponentsList_dependencies= GaudiAlg 
CLHEP_tag=$(tag)
CLHEPROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/CLHEP
CLHEP_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/CLHEP
CLHEPVERSION=v1
CLHEP_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
CLHEP_offset=LCG_Interfaces
CLHEP_project=LCGCMT
CLHEP_project_release=LCGCMT_84
CLHEP_native_version=$(CLHEP_config_version)
CLHEP_home=$(LCG_external)/clhep/$(CLHEP_native_version)/$(LCG_system)
CLHEP_include=$(CLHEP_home)/include
CLHEP_linkopts=-L$(CLHEP_home)/lib         -lCLHEP-Cast-$(CLHEP_native_version)        -lCLHEP-Evaluator-$(CLHEP_native_version)        -lCLHEP-Exceptions-$(CLHEP_native_version)        -lCLHEP-GenericFunctions-$(CLHEP_native_version)        -lCLHEP-Geometry-$(CLHEP_native_version)        -lCLHEP-Random-$(CLHEP_native_version)        -lCLHEP-RandomObjects-$(CLHEP_native_version)        -lCLHEP-RefCount-$(CLHEP_native_version)         -lCLHEP-Vector-$(CLHEP_native_version)        -lCLHEP-Matrix-$(CLHEP_native_version)  
CLHEP_name=clhep
CLHEP_export_paths=$(CLHEP_home)/include $(CLHEP_home)/lib
GaudiGSL_linkopts= -lGaudiGSLLib 
GaudiGSL_stamps=${GAUDIGSLROOT}/${BINDIR}/GaudiGSLLib.stamp 
GaudiGSL_linker_library=GaudiGSLLib
GaudiGSLMathDict_shlibflags= $(GaudiGSL_linkopts) 
GaudiPython_tag=$(tag)
GAUDIPYTHONROOT=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiPython
GaudiPython_root=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/GaudiPython
GAUDIPYTHONVERSION=v14r2
GaudiPython_cmtpath=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1
GaudiPython_project=GAUDI
GaudiPython_project_release=GAUDI_v27r1
zip_GaudiPython_python_modules_dependencies= GaudiPython_python_init 
GaudiPython_python_init_dependencies= GaudiPython_python 
GaudiPython_linkopts= -lGaudiPythonLib 
GaudiPython_stamps=${GAUDIPYTHONROOT}/${BINDIR}/GaudiPythonLib.stamp 
GaudiPython_linker_library=GaudiPythonLib
pyanalysis_tag=$(tag)
PYANALYSISROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/pyanalysis
pyanalysis_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/pyanalysis
PYANALYSISVERSION=v1
pyanalysis_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
pyanalysis_offset=LCG_Interfaces
pyanalysis_project=LCGCMT
pyanalysis_project_release=LCGCMT_84
blas_tag=$(tag)
BLASROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/blas
blas_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/blas
BLASVERSION=v1
blas_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
blas_offset=LCG_Interfaces
blas_project=LCGCMT
blas_project_release=LCGCMT_84
blas_native_version=$(blas_config_version)
blas_home=$(LCG_external)/blas/$(blas_native_version)/$(LCG_system)
BLAS=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/blas/20110419/x86_64-slc6-gcc48-opt
blas_linkopts= -L$(blas_home)/lib -lBLAS 
lapack_tag=$(tag)
LAPACKROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/lapack
lapack_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/lapack
LAPACKVERSION=v1
lapack_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
lapack_offset=LCG_Interfaces
lapack_project=LCGCMT
lapack_project_release=LCGCMT_84
lapack_native_version=$(lapack_config_version)
lapack_home=$(LCG_external)/lapack/$(lapack_native_version)/$(LCG_system)
LAPACK=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/lapack/3.5.0/x86_64-slc6-gcc48-opt
lapack_linkopts= -L$(lapack_home)/lib -lLAPACK 
pyanalysis_native_version=$(pyanalysis_config_version)_python$(Python_config_version_twodigit)
pyanalysis_home=$(LCG_external)/pyanalysis/$(pyanalysis_native_version)/$(LCG_system)
pyanalysis_export_paths=$(pyanalysis_home)
zip_LHCbMath_python_modules_dependencies= LHCbMath_python_init 
LHCbMath_python_init_dependencies= LHCbMath_python 
TestPow_dependencies= LHCbMathLib 
TestBit_dependencies= LHCbMathLib 
TestDigit_dependencies= LHCbMathLib 
TestKine_dependencies= LHCbMathLib 
TestLomont_dependencies= LHCbMathLib 
TestErrors_dependencies= LHCbMathLib 
TestRound_dependencies= LHCbMathLib 
TestLomont2_dependencies= LHCbMathLib 
TestEigen_dependencies= LHCbMathLib 
TestBlind_dependencies= LHCbMathLib 
TestAbs_dependencies= LHCbMathLib 
TestChi2_dependencies= LHCbMathLib 
TestHesse_dependencies= LHCbMathLib 
TestChi2Fit_dependencies= LHCbMathLib 
TestLABug_dependencies= LHCbMathLib 
TestBloomFilter_dependencies= LHCbMathLib 
TestSimilarity_dependencies= LHCbMathLib 
TestEigenGeometry_dependencies= LHCbMathLib 
TestXYZTypes_dependencies= LHCbMathLib 
LHCbMath_linkopts= -lLHCbMathLib 
LHCbMath_stamps=${LHCBMATHROOT}/${BINDIR}/LHCbMathLib.stamp 
LHCbMath_linker_library=LHCbMathLib
LHCbMathDict_dependencies= LHCbMathLib 
LHCbMath_use_linkopts=$(use_linkopts)
Similarity_AVX_cppflags= -mavx  -O3 -fabi-version=0 
Similarity_SSE3_cppflags= -msse3 -O3 
Similarity_generic_cppflags= -O3 
GaudiObjDesc_tag=$(tag)
GAUDIOBJDESCROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/GaudiObjDesc
GaudiObjDesc_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/GaudiObjDesc
GAUDIOBJDESCVERSION=v11r24
GaudiObjDesc_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
GaudiObjDesc_project=LHCB
GaudiObjDesc_project_release=LHCB_v40r1
xmlsrc=xml
pytools_tag=$(tag)
PYTOOLSROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/pytools
pytools_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/pytools
PYTOOLSVERSION=v1
pytools_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
pytools_offset=LCG_Interfaces
pytools_project=LCGCMT
pytools_project_release=LCGCMT_84
mysql_tag=$(tag)
MYSQLROOT=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/mysql
mysql_root=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Interfaces/mysql
MYSQLVERSION=v1
mysql_cmtpath=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
mysql_offset=LCG_Interfaces
mysql_project=LCGCMT
mysql_project_release=LCGCMT_84
mysql_native_version=$(mysql_config_version)
mysql_home=$(LCG_external)/mysql/$(mysql_native_version)/$(LCG_system)
mysql_include=$(mysql_home)/include
mysql_linkopts=-L$(mysql_home)/lib -lmysqlclient_r 
mysql_export_paths= $(mysql_home)/include $(mysql_home)/lib 
pytools_native_version=$(pytools_config_version)_python$(Python_config_version_twodigit)
pytools_home=$(LCG_external)/pytools/$(pytools_native_version)/$(LCG_system)
pytools_export_paths=$(pytools_home)
zip_GaudiObjDesc_python_modules_dependencies= GaudiObjDesc_python_init 
GaudiObjDesc_python_init_dependencies= GaudiObjDesc_python 
GaudiObjDesc_linkopts= -lGaudiObjDescLib 
GaudiObjDesc_stamps=${GAUDIOBJDESCROOT}/${BINDIR}/GaudiObjDescLib.stamp 
GaudiObjDesc_linker_library=GaudiObjDescLib
LHCbKernelObj2Doth_GODflags= -s ../Kernel/ 
LHCbKernel_dependencies=LHCbKernelObj2Doth
install_more_includes_dependencies= LHCbKernelObj2Doth  EventBaseObj2Doth  DigiEventObj2Doth  TrackEventObj2Doth  RecEventObj2Doth  DAQEventObj2Doth 
zip_LHCbKernel_python_modules_dependencies= LHCbKernel_python_init 
LHCbKernel_python_init_dependencies= LHCbKernel_python 
LHCbKernelObj2Dict_dependencies=LHCbKernelCustomDict
LHCbKernelObj2Dict_GODflags= -s ../Kernel/ 
LHCbKernelGen_dependencies=LHCbKernelObj2Doth LHCbKernelObj2Dict
LHCbKernel_linkopts= -lLHCbKernel 
LHCbKernel_stamps=${LHCBKERNELROOT}/${BINDIR}/LHCbKernel.stamp 
LHCbKernel_linker_library=LHCbKernel
RichSmartIDTest_dependencies= LHCbKernel 
EventBase_dependencies=EventBaseObj2Doth
EventBaseGen_dependencies=EventBaseObj2Doth EventBaseObj2Dict
DigiEvent_tag=$(tag)
DIGIEVENTROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Event/DigiEvent
DigiEvent_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Event/DigiEvent
DIGIEVENTVERSION=v4r5
DigiEvent_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
DigiEvent_offset=Event
DigiEvent_project=LHCB
DigiEvent_project_release=LHCB_v40r1
DigiEvent_dependencies=DigiEventObj2Doth
DigiEventObj2Dict_dependencies=DigiEventCustomDict
DigiEventGen_dependencies=DigiEventObj2Doth DigiEventObj2Dict
TrackEvent_tag=$(tag)
TRACKEVENTROOT=/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/Event/TrackEvent
TrackEvent_root=/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/Event/TrackEvent
TRACKEVENTVERSION=v6r7
TrackEvent_cmtpath=/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2
TrackEvent_offset=Event
TrackEvent_project=REC
TrackEvent_project_release=REC_v19r2
TrackEvent_dependencies=TrackEventObj2Doth
TrackEventObj2Dict_dependencies=TrackEventCustomDict
TrackEventGen_dependencies=TrackEventObj2Doth TrackEventObj2Dict
TrackEvent_linkopts= -lTrackEvent 
TrackEvent_stamps=${TRACKEVENTROOT}/${BINDIR}/TrackEvent.stamp 
TrackEvent_linker_library=TrackEvent
PartProp_tag=$(tag)
PARTPROPROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Kernel/PartProp
PartProp_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Kernel/PartProp
PARTPROPVERSION=v1r21
PartProp_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
PartProp_offset=Kernel
PartProp_project=LHCB
PartProp_project_release=LHCB_v40r1
zip_PartProp_python_modules_dependencies= PartProp_python_init 
PartProp_python_init_dependencies= PartProp_python 
PartProp_dependencies=$(PartProp_linker_library)  PartPropLib 
PartPropDict_dependencies= PartPropLib 
PartProp_linkopts= -lPartPropLib 
PartProp_stamps=${PARTPROPROOT}/${BINDIR}/PartPropLib.stamp 
PartProp_linker_library=PartPropLib
PartPropComponentsList_dependencies= PartProp 
dump_particle_properties=dump_ParticleProperties
ParticleProperties=dump_ParticleProperties
ParticlePropertiesTable=dump_ParticleProperties
RecEvent_dependencies=RecEventObj2Doth
RecEventObj2Dict_dependencies=RecEventCustomDict
RecEventGen_dependencies=RecEventObj2Doth RecEventObj2Dict
RecEvent_linkopts= -lRecEvent 
RecEvent_stamps=${RECEVENTROOT}/${BINDIR}/RecEvent.stamp 
RecEvent_linker_library=RecEvent
TfKernel_tag=$(tag)
TFKERNELROOT=/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/Tf/TfKernel
TfKernel_root=/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/Tf/TfKernel
TFKERNELVERSION=v2r35
TfKernel_cmtpath=/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2
TfKernel_offset=Tf
TfKernel_project=REC
TfKernel_project_release=REC_v19r2
DAQEvent_tag=$(tag)
DAQEVENTROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Event/DAQEvent
DAQEvent_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Event/DAQEvent
DAQEVENTVERSION=v9r22
DAQEvent_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
DAQEvent_offset=Event
DAQEvent_project=LHCB
DAQEvent_project_release=LHCB_v40r1
DAQEvent_dependencies=DAQEventObj2Doth
DAQEventGen_dependencies=DAQEventObj2Doth
DAQEventLib_dependencies=DAQEventObj2Doth
DAQEvent_linkopts= -lDAQEventLib 
DAQEvent_stamps=${DAQEVENTROOT}/${BINDIR}/DAQEventLib.stamp 
DAQEvent_linker_library=DAQEventLib
OTDet_tag=$(tag)
OTDETROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Det/OTDet
OTDet_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Det/OTDet
OTDETVERSION=v9r0
OTDet_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
OTDet_offset=Det
OTDet_project=LHCB
OTDet_project_release=LHCB_v40r1
DetDescCnv_tag=$(tag)
DETDESCCNVROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Det/DetDescCnv
DetDescCnv_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Det/DetDescCnv
DETDESCCNVVERSION=v4r19
DetDescCnv_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
DetDescCnv_offset=Det
DetDescCnv_project=LHCB
DetDescCnv_project_release=LHCB_v40r1
DetDesc_tag=$(tag)
DETDESCROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Det/DetDesc
DetDesc_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Det/DetDesc
DETDESCVERSION=v19r1
DetDesc_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
DetDesc_offset=Det
DetDesc_project=LHCB
DetDesc_project_release=LHCB_v40r1
DetDesc_linkopts= -lDetDescLib 
DetDesc_stamps=${DETDESCROOT}/${BINDIR}/DetDescLib.stamp 
DetDesc_linker_library=DetDescLib
XmlTools_tag=$(tag)
XMLTOOLSROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Tools/XmlTools
XmlTools_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Tools/XmlTools
XMLTOOLSVERSION=v6r9
XmlTools_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
XmlTools_offset=Tools
XmlTools_project=LHCB
XmlTools_project_release=LHCB_v40r1
XmlTools_dependencies=$(XmlTools_linker_library) 
XmlToolsComponentsList_dependencies= XmlTools 
XmlTools_linkopts= -lXmlToolsLib 
XmlTools_stamps=${XMLTOOLSROOT}/${BINDIR}/XmlToolsLib.stamp 
XmlTools_linker_library=XmlToolsLib
DetDescCnv_dependencies=$(DetDescCnv_linker_library) 
DetDescCnvComponentsList_dependencies= DetDescCnv 
DetDescCnv_linkopts= -lDetDescCnvLib 
DetDescCnv_stamps=${DETDESCCNVROOT}/${BINDIR}/DetDescCnvLib.stamp 
DetDescCnv_linker_library=DetDescCnvLib
OTDet_dependencies=$(OTDet_linker_library) 
OTDetComponentsList_dependencies= OTDet 
OTDet_linkopts= -lOTDetLib 
OTDet_stamps=${OTDETROOT}/${BINDIR}/OTDetLib.stamp 
OTDet_linker_library=OTDetLib
STDet_tag=$(tag)
STDETROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Det/STDet
STDet_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Det/STDet
STDETVERSION=v5r1
STDet_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
STDet_offset=Det
STDet_project=LHCB
STDet_project_release=LHCB_v40r1
STDet_dependencies=$(STDet_linker_library) 
STDetComponentsList_dependencies= STDet 
STDet_linkopts= -lSTDetLib 
STDet_stamps=${STDETROOT}/${BINDIR}/STDetLib.stamp 
STDet_linker_library=STDetLib
VeloDet_tag=$(tag)
VELODETROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Det/VeloDet
VeloDet_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/Det/VeloDet
VELODETVERSION=v14r1
VeloDet_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
VeloDet_offset=Det
VeloDet_project=LHCB
VeloDet_project_release=LHCB_v40r1
VeloDet_dependencies=$(VeloDet_linker_library) 
VeloDetComponentsList_dependencies= VeloDet 
VeloDet_linkopts= -lVeloDetLib 
VeloDet_stamps=${VELODETROOT}/${BINDIR}/VeloDetLib.stamp 
VeloDet_linker_library=VeloDetLib
OTDAQ_tag=$(tag)
OTDAQROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/OT/OTDAQ
OTDAQ_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/OT/OTDAQ
OTDAQVERSION=v8r1
OTDAQ_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
OTDAQ_offset=OT
OTDAQ_project=LHCB
OTDAQ_project_release=LHCB_v40r1
DAQKernel_tag=$(tag)
DAQKERNELROOT=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/DAQ/DAQKernel
DAQKernel_root=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/DAQ/DAQKernel
DAQKERNELVERSION=v1r1
DAQKernel_cmtpath=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
DAQKernel_offset=DAQ
DAQKernel_project=LHCB
DAQKernel_project_release=LHCB_v40r1
DAQKernel_linkopts= -lDAQKernelLib 
DAQKernel_stamps=${DAQKERNELROOT}/${BINDIR}/DAQKernelLib.stamp 
DAQKernel_linker_library=DAQKernelLib
OTDAQ_dependencies=$(OTDAQ_linker_library) 
OTDAQComponentsList_dependencies= OTDAQ 
PrKernel_linkopts= -lPrKernel 
PrKernel_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(PrKernel_use_linkopts) -Wl,-soname=$(library_prefix)PrKernel.$(shlibsuffix) 
PrKernel_use_linkopts=    $(TfKernel_linkopts)  $(RecEvent_linkopts)  $(EventBase_linkopts)  $(OTDAQ_linkopts)  $(DigiEvent_linkopts)  $(TrackEvent_linkopts)  $(OTDet_linkopts)  $(STDet_linkopts)  $(VeloDet_linkopts)  $(DAQKernel_linkopts)  $(LHCbKernel_linkopts)  $(PartProp_linkopts)  $(DetDescCnv_linkopts)  $(DetDesc_linkopts)  $(LHCbMath_linkopts)  $(GaudiGSL_linkopts)  $(GaudiAlg_linkopts)  $(GaudiUtils_linkopts)  $(GaudiObjDesc_linkopts)  $(DAQEvent_linkopts)  $(XmlTools_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPluginService_linkopts)  $(VectorClass_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(pyanalysis_linkopts)  $(pytools_linkopts)  $(Python_linkopts)  $(xrootd_linkopts)  $(tbb_linkopts)  $(GSL_linkopts)  $(vdt_linkopts)  $(eigen_linkopts)  $(XercesC_linkopts)  $(CLHEP_linkopts)  $(lapack_linkopts)  $(blas_linkopts)  $(mysql_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts) 
PrKernel_stamps=${PRKERNELROOT}/${BINDIR}/PrKernel.stamp 
PrKernel_linker_library=PrKernel
lib_PrKernel_pp_cppflags= -DGAUDI_LINKER_LIBRARY 
PrKernelexportsymb=-export_all_symbols
PrKernelinstalllib=yes
PrKernel_reflex_selection_file= $(PRKERNELROOT)/dict/PrKernelDict.xml 
PrKernel_rootmap=$(CMTINSTALLAREA)/$(tag)/lib/Brunel_v50r1Dict.rootmap
PrKernel_reflex_options= -U__MINGW32__ -U_Instantiations -D_Instantiations=PrKernel_Instantiations $(gccxmlopts) --select=$(PRKERNELROOT)/dict/PrKernelDict.xml  --gccxmlpath=$(GCCXML_home)/bin
PrKernelDict_dependencies=$(PrKernel_linker_library) PrKernelGen
PrKernelDict_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(PrKernel_linkopts) $(PrKernelDict_use_linkopts) 
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
GaudiPluginServiceDir=${GAUDIPLUGINSERVICEROOT}/${BINDIR}
GaudiKernelDir=${GAUDIKERNELROOT}/${BINDIR}
VectorClassDir=${VECTORCLASSROOT}/${BINDIR}
GaudiUtilsDir=${GAUDIUTILSROOT}/${BINDIR}
GaudiAlgDir=${GAUDIALGROOT}/${BINDIR}
GaudiGSLDir=${GAUDIGSLROOT}/${BINDIR}
GaudiPythonDir=${GAUDIPYTHONROOT}/${BINDIR}
LHCbMathDir=${LHCBMATHROOT}/${BINDIR}
GaudiObjDescDir=${GAUDIOBJDESCROOT}/${BINDIR}
LHCbKernelDir=${LHCBKERNELROOT}/${BINDIR}
EventBaseDir=${EVENTBASEROOT}/${BINDIR}
DigiEventDir=${DIGIEVENTROOT}/${BINDIR}
TrackEventDir=${TRACKEVENTROOT}/${BINDIR}
PartPropDir=${PARTPROPROOT}/${BINDIR}
RecEventDir=${RECEVENTROOT}/${BINDIR}
DAQEventDir=${DAQEVENTROOT}/${BINDIR}
DetDescDir=${DETDESCROOT}/${BINDIR}
XmlToolsDir=${XMLTOOLSROOT}/${BINDIR}
DetDescCnvDir=${DETDESCCNVROOT}/${BINDIR}
OTDetDir=${OTDETROOT}/${BINDIR}
STDetDir=${STDETROOT}/${BINDIR}
VeloDetDir=${VELODETROOT}/${BINDIR}
DAQKernelDir=${DAQKERNELROOT}/${BINDIR}
OTDAQDir=${OTDAQROOT}/${BINDIR}
TfKernelDir=${TFKERNELROOT}/${BINDIR}
PrKernelDir=${PRKERNELROOT}/${BINDIR}
generate_manifest_file_output=$(CMTINSTALLAREA)/$(tag)/manifest.xml
generate_manifest_file_deps=FORCE
generate_manifest_file_command=python $(GaudiPolicy_root)/scripts/project_manifest.py -o $(generate_manifest_file_output) $(PrKernel_cmtpath)/CMakeLists.txt $(LCG_config_version) $(tag)
generate_manifest_file_applied=NullCommand
dummy_for_NullCommand=generate_manifest_file 
tag=x86_64-slc6-gcc48-opt
package=PrKernel
version=v1r10
PACKAGE_ROOT=$(PRKERNELROOT)
srcdir=../src
bin=../$(PrKernel_tag)/
BIN=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/Pr/PrKernel/$(PrKernel_tag)/
javabin=../classes/
mgrdir=cmt
project=Brunel_v50r1
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(LHCB_installarea_prefix)/$(CMTCONFIG)/lib $(LHCB_installarea_prefix)/share/lib $(LHCB_installarea_prefix)/share/bin $(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib $(LBCOM_installarea_prefix)/share/lib $(LBCOM_installarea_prefix)/share/bin $(REC_installarea_prefix)/$(CMTCONFIG)/lib $(REC_installarea_prefix)/share/lib $(REC_installarea_prefix)/share/bin $(BRUNEL_installarea_prefix)/$(CMTCONFIG)/lib $(BRUNEL_installarea_prefix)/share/lib $(BRUNEL_installarea_prefix)/share/bin $(Brunel_v50r1_installarea_prefix)/$(CMTCONFIG)/lib $(Brunel_v50r1_installarea_prefix)/share/lib $(Brunel_v50r1_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(PrKernel_linkopts)  $(TfKernel_linkopts)  $(RecEvent_linkopts)  $(EventBase_linkopts)  $(OTDAQ_linkopts)  $(DigiEvent_linkopts)  $(TrackEvent_linkopts)  $(OTDet_linkopts)  $(STDet_linkopts)  $(VeloDet_linkopts)  $(DAQKernel_linkopts)  $(LHCbKernel_linkopts)  $(PartProp_linkopts)  $(DetDescCnv_linkopts)  $(DetDesc_linkopts)  $(LHCbMath_linkopts)  $(GaudiGSL_linkopts)  $(GaudiAlg_linkopts)  $(GaudiUtils_linkopts)  $(GaudiObjDesc_linkopts)  $(DAQEvent_linkopts)  $(XmlTools_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPluginService_linkopts)  $(VectorClass_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(pyanalysis_linkopts)  $(pytools_linkopts)  $(Python_linkopts)  $(xrootd_linkopts)  $(tbb_linkopts)  $(GSL_linkopts)  $(vdt_linkopts)  $(eigen_linkopts)  $(XercesC_linkopts)  $(CLHEP_linkopts)  $(lapack_linkopts)  $(blas_linkopts)  $(mysql_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
PARAM_installarea_prefix=$(cmt_installarea_prefix)
PARAM_installarea_prefix_remove=$(PARAM_installarea_prefix)
DBASE_installarea_prefix=$(cmt_installarea_prefix)
DBASE_installarea_prefix_remove=$(DBASE_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
LHCB_installarea_prefix=$(cmt_installarea_prefix)
LHCB_installarea_prefix_remove=$(LHCB_installarea_prefix)
LBCOM_installarea_prefix=$(cmt_installarea_prefix)
LBCOM_installarea_prefix_remove=$(LBCOM_installarea_prefix)
REC_installarea_prefix=$(cmt_installarea_prefix)
REC_installarea_prefix_remove=$(REC_installarea_prefix)
BRUNEL_installarea_prefix=$(cmt_installarea_prefix)
BRUNEL_installarea_prefix_remove=$(BRUNEL_installarea_prefix)
Brunel_v50r1_installarea_prefix=$(cmt_installarea_prefix)
Brunel_v50r1_installarea_prefix_remove=$(Brunel_v50r1_installarea_prefix)
cmt_installarea_linkopts= -L/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/$(Brunel_v50r1_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/$(BRUNEL_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/$(REC_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/$(LBCOM_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/$(LHCB_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib 
LCGCMT_home=/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84
PARAM_home=/afs/cern.ch/lhcb/software/releases/PARAM
DBASE_home=/afs/cern.ch/lhcb/software/releases/DBASE
GAUDI_home=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1
LHCB_home=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1
LBCOM_home=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1
REC_home=/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2
BRUNEL_home=/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1
Brunel_v50r1_home=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1
Brunel_v50r1_install_include=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/$(Brunel_v50r1_installarea_prefix)$(shared_install_subdir)/include
BRUNEL_install_include=/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/$(BRUNEL_installarea_prefix)$(shared_install_subdir)/include
REC_install_include=/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/$(REC_installarea_prefix)$(shared_install_subdir)/include
LBCOM_install_include=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/$(LBCOM_installarea_prefix)$(shared_install_subdir)/include
LHCB_install_include=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/$(LHCB_installarea_prefix)$(shared_install_subdir)/include
GAUDI_install_include=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/$(GAUDI_installarea_prefix)$(shared_install_subdir)/include
GAUDI_install_python=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/$(GAUDI_installarea_prefix)$(shared_install_subdir)/python.zip
LHCB_install_python=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/$(LHCB_installarea_prefix)$(shared_install_subdir)/python.zip
LBCOM_install_python=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/$(LBCOM_installarea_prefix)$(shared_install_subdir)/python.zip
REC_install_python=/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/$(REC_installarea_prefix)$(shared_install_subdir)/python.zip
BRUNEL_install_python=/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/$(BRUNEL_installarea_prefix)$(shared_install_subdir)/python.zip
Brunel_v50r1_install_python=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/$(Brunel_v50r1_installarea_prefix)$(shared_install_subdir)/python.zip
GAUDI_install_pyd_module=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/$(GAUDI_installarea_prefix)/$(python_bin_module_dir)
LHCB_install_pyd_module=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/$(LHCB_installarea_prefix)/$(python_bin_module_dir)
LBCOM_install_pyd_module=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/$(LBCOM_installarea_prefix)/$(python_bin_module_dir)
REC_install_pyd_module=/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/$(REC_installarea_prefix)/$(python_bin_module_dir)
BRUNEL_install_pyd_module=/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/$(BRUNEL_installarea_prefix)/$(python_bin_module_dir)
Brunel_v50r1_install_pyd_module=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/$(Brunel_v50r1_installarea_prefix)/$(python_bin_module_dir)
scripts_offset=.
scripts_maindir=scripts
scripts_dir=$(scripts_maindir)
GAUDI_install_scripts=/afs/cern.ch/lhcb/software/releases/GAUDI/GAUDI_v27r1/$(GAUDI_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
LHCB_install_scripts=/afs/cern.ch/lhcb/software/releases/LHCB/LHCB_v40r1/$(LHCB_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
LBCOM_install_scripts=/afs/cern.ch/lhcb/software/releases/LBCOM/LBCOM_v18r1/$(LBCOM_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
REC_install_scripts=/afs/cern.ch/lhcb/software/releases/REC/REC_v19r2/$(REC_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
BRUNEL_install_scripts=/afs/cern.ch/lhcb/software/releases/BRUNEL/BRUNEL_v50r1/$(BRUNEL_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
Brunel_v50r1_install_scripts=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/$(Brunel_v50r1_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
genconfInstallDir=$(CMTINSTALLAREA)$(shared_install_subdir)/python
CMTINSTALLAREA=/users/LHCb/abdulkhalek/cmtuser/Brunel_v50r1/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(TfKernel_root)/cmt/requirements $(RecEvent_root)/cmt/requirements $(EventBase_root)/cmt/requirements $(OTDAQ_root)/cmt/requirements $(DigiEvent_root)/cmt/requirements $(TrackEvent_root)/cmt/requirements $(OTDet_root)/cmt/requirements $(STDet_root)/cmt/requirements $(VeloDet_root)/cmt/requirements $(DAQKernel_root)/cmt/requirements $(LHCbKernel_root)/cmt/requirements $(PartProp_root)/cmt/requirements $(DetDescCnv_root)/cmt/requirements $(DetDesc_root)/cmt/requirements $(LHCbMath_root)/cmt/requirements $(GaudiGSL_root)/cmt/requirements $(GaudiPython_root)/cmt/requirements $(GaudiAlg_root)/cmt/requirements $(GaudiUtils_root)/cmt/requirements $(GaudiObjDesc_root)/cmt/requirements $(DAQEvent_root)/cmt/requirements $(XmlTools_root)/cmt/requirements $(GaudiKernel_root)/cmt/requirements $(GaudiPluginService_root)/cmt/requirements $(VectorClass_root)/cmt/requirements $(GaudiPolicy_root)/cmt/requirements $(Reflex_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(Boost_root)/cmt/requirements $(pyanalysis_root)/cmt/requirements $(pytools_root)/cmt/requirements $(Python_root)/cmt/requirements $(tcmalloc_root)/cmt/requirements $(libunwind_root)/cmt/requirements $(xrootd_root)/cmt/requirements $(tbb_root)/cmt/requirements $(GSL_root)/cmt/requirements $(vdt_root)/cmt/requirements $(eigen_root)/cmt/requirements $(AIDA_root)/cmt/requirements $(uuid_root)/cmt/requirements $(XercesC_root)/cmt/requirements $(CLHEP_root)/cmt/requirements $(lapack_root)/cmt/requirements $(blas_root)/cmt/requirements $(mysql_root)/cmt/requirements $(LCG_Settings_root)/cmt/requirements $(LCG_Configuration_root)/cmt/requirements $(LCG_Platforms_root)/cmt/requirements 
use_includes= $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/ROOT/6.06.02/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/ROOT/6.06.02/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/Boost/1.59.0_python2.7/x86_64-slc6-gcc48-opt/include/boost-1_59" $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/Python/2.7.10/x86_64-slc6-gcc48-opt/include/python2.7" $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/xrootd/4.2.3/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/tbb/42_20140122/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/GSL/1.10/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/vdt/0.3.6/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/eigen/3.2.7/x86_64-slc6-gcc48-opt/include/eigen3" $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/XercesC/3.1.1p1/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/clhep/2.3.1.1/x86_64-slc6-gcc48-opt/include" $(ppcmd)"/afs/cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_84/LCG_Settings/../../../LCG_84/mysql/5.5.30/x86_64-slc6-gcc48-opt/include" $(ppcmd)"$(LCG_Platforms_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(PrKernel_stamps)  $(TfKernel_stamps)  $(RecEvent_stamps)  $(EventBase_stamps)  $(OTDAQ_stamps)  $(DigiEvent_stamps)  $(TrackEvent_stamps)  $(OTDet_stamps)  $(STDet_stamps)  $(VeloDet_stamps)  $(DAQKernel_stamps)  $(LHCbKernel_stamps)  $(PartProp_stamps)  $(DetDescCnv_stamps)  $(DetDesc_stamps)  $(LHCbMath_stamps)  $(GaudiGSL_stamps)  $(GaudiAlg_stamps)  $(GaudiUtils_stamps)  $(GaudiObjDesc_stamps)  $(DAQEvent_stamps)  $(XmlTools_stamps)  $(GaudiKernel_stamps)  $(GaudiPluginService_stamps)  $(VectorClass_stamps)  $(GaudiPolicy_stamps)  $(Reflex_stamps)  $(ROOT_stamps)  $(Boost_stamps)  $(pyanalysis_stamps)  $(pytools_stamps)  $(Python_stamps)  $(xrootd_stamps)  $(tbb_stamps)  $(GSL_stamps)  $(vdt_stamps)  $(eigen_stamps)  $(XercesC_stamps)  $(CLHEP_stamps)  $(lapack_stamps)  $(blas_stamps)  $(mysql_stamps)  $(LCG_Settings_stamps)  $(LCG_Configuration_stamps)  $(LCG_Platforms_stamps) 
use_cflags=  $(PrKernel_cflags)  $(TfKernel_cflags)  $(RecEvent_cflags)  $(EventBase_cflags)  $(OTDAQ_cflags)  $(DigiEvent_cflags)  $(TrackEvent_cflags)  $(OTDet_cflags)  $(STDet_cflags)  $(VeloDet_cflags)  $(DAQKernel_cflags)  $(LHCbKernel_cflags)  $(PartProp_cflags)  $(DetDescCnv_cflags)  $(DetDesc_cflags)  $(LHCbMath_cflags)  $(GaudiGSL_cflags)  $(GaudiAlg_cflags)  $(GaudiUtils_cflags)  $(GaudiObjDesc_cflags)  $(DAQEvent_cflags)  $(XmlTools_cflags)  $(GaudiKernel_cflags)  $(GaudiPluginService_cflags)  $(VectorClass_cflags)  $(GaudiPolicy_cflags)  $(Reflex_cflags)  $(ROOT_cflags)  $(Boost_cflags)  $(pyanalysis_cflags)  $(pytools_cflags)  $(Python_cflags)  $(xrootd_cflags)  $(tbb_cflags)  $(GSL_cflags)  $(vdt_cflags)  $(eigen_cflags)  $(XercesC_cflags)  $(CLHEP_cflags)  $(lapack_cflags)  $(blas_cflags)  $(mysql_cflags)  $(LCG_Settings_cflags)  $(LCG_Configuration_cflags)  $(LCG_Platforms_cflags) 
use_pp_cflags=  $(PrKernel_pp_cflags)  $(TfKernel_pp_cflags)  $(RecEvent_pp_cflags)  $(EventBase_pp_cflags)  $(OTDAQ_pp_cflags)  $(DigiEvent_pp_cflags)  $(TrackEvent_pp_cflags)  $(OTDet_pp_cflags)  $(STDet_pp_cflags)  $(VeloDet_pp_cflags)  $(DAQKernel_pp_cflags)  $(LHCbKernel_pp_cflags)  $(PartProp_pp_cflags)  $(DetDescCnv_pp_cflags)  $(DetDesc_pp_cflags)  $(LHCbMath_pp_cflags)  $(GaudiGSL_pp_cflags)  $(GaudiAlg_pp_cflags)  $(GaudiUtils_pp_cflags)  $(GaudiObjDesc_pp_cflags)  $(DAQEvent_pp_cflags)  $(XmlTools_pp_cflags)  $(GaudiKernel_pp_cflags)  $(GaudiPluginService_pp_cflags)  $(VectorClass_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(Reflex_pp_cflags)  $(ROOT_pp_cflags)  $(Boost_pp_cflags)  $(pyanalysis_pp_cflags)  $(pytools_pp_cflags)  $(Python_pp_cflags)  $(xrootd_pp_cflags)  $(tbb_pp_cflags)  $(GSL_pp_cflags)  $(vdt_pp_cflags)  $(eigen_pp_cflags)  $(XercesC_pp_cflags)  $(CLHEP_pp_cflags)  $(lapack_pp_cflags)  $(blas_pp_cflags)  $(mysql_pp_cflags)  $(LCG_Settings_pp_cflags)  $(LCG_Configuration_pp_cflags)  $(LCG_Platforms_pp_cflags) 
use_cppflags=  $(PrKernel_cppflags)  $(TfKernel_cppflags)  $(RecEvent_cppflags)  $(EventBase_cppflags)  $(OTDAQ_cppflags)  $(DigiEvent_cppflags)  $(TrackEvent_cppflags)  $(OTDet_cppflags)  $(STDet_cppflags)  $(VeloDet_cppflags)  $(DAQKernel_cppflags)  $(LHCbKernel_cppflags)  $(PartProp_cppflags)  $(DetDescCnv_cppflags)  $(DetDesc_cppflags)  $(LHCbMath_cppflags)  $(GaudiGSL_cppflags)  $(GaudiAlg_cppflags)  $(GaudiUtils_cppflags)  $(GaudiObjDesc_cppflags)  $(DAQEvent_cppflags)  $(XmlTools_cppflags)  $(GaudiKernel_cppflags)  $(GaudiPluginService_cppflags)  $(VectorClass_cppflags)  $(GaudiPolicy_cppflags)  $(Reflex_cppflags)  $(ROOT_cppflags)  $(Boost_cppflags)  $(pyanalysis_cppflags)  $(pytools_cppflags)  $(Python_cppflags)  $(xrootd_cppflags)  $(tbb_cppflags)  $(GSL_cppflags)  $(vdt_cppflags)  $(eigen_cppflags)  $(XercesC_cppflags)  $(CLHEP_cppflags)  $(lapack_cppflags)  $(blas_cppflags)  $(mysql_cppflags)  $(LCG_Settings_cppflags)  $(LCG_Configuration_cppflags)  $(LCG_Platforms_cppflags) 
use_pp_cppflags=  $(PrKernel_pp_cppflags)  $(TfKernel_pp_cppflags)  $(RecEvent_pp_cppflags)  $(EventBase_pp_cppflags)  $(OTDAQ_pp_cppflags)  $(DigiEvent_pp_cppflags)  $(TrackEvent_pp_cppflags)  $(OTDet_pp_cppflags)  $(STDet_pp_cppflags)  $(VeloDet_pp_cppflags)  $(DAQKernel_pp_cppflags)  $(LHCbKernel_pp_cppflags)  $(PartProp_pp_cppflags)  $(DetDescCnv_pp_cppflags)  $(DetDesc_pp_cppflags)  $(LHCbMath_pp_cppflags)  $(GaudiGSL_pp_cppflags)  $(GaudiAlg_pp_cppflags)  $(GaudiUtils_pp_cppflags)  $(GaudiObjDesc_pp_cppflags)  $(DAQEvent_pp_cppflags)  $(XmlTools_pp_cppflags)  $(GaudiKernel_pp_cppflags)  $(GaudiPluginService_pp_cppflags)  $(VectorClass_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(Reflex_pp_cppflags)  $(ROOT_pp_cppflags)  $(Boost_pp_cppflags)  $(pyanalysis_pp_cppflags)  $(pytools_pp_cppflags)  $(Python_pp_cppflags)  $(xrootd_pp_cppflags)  $(tbb_pp_cppflags)  $(GSL_pp_cppflags)  $(vdt_pp_cppflags)  $(eigen_pp_cppflags)  $(XercesC_pp_cppflags)  $(CLHEP_pp_cppflags)  $(lapack_pp_cppflags)  $(blas_pp_cppflags)  $(mysql_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(LCG_Configuration_pp_cppflags)  $(LCG_Platforms_pp_cppflags) 
use_fflags=  $(PrKernel_fflags)  $(TfKernel_fflags)  $(RecEvent_fflags)  $(EventBase_fflags)  $(OTDAQ_fflags)  $(DigiEvent_fflags)  $(TrackEvent_fflags)  $(OTDet_fflags)  $(STDet_fflags)  $(VeloDet_fflags)  $(DAQKernel_fflags)  $(LHCbKernel_fflags)  $(PartProp_fflags)  $(DetDescCnv_fflags)  $(DetDesc_fflags)  $(LHCbMath_fflags)  $(GaudiGSL_fflags)  $(GaudiAlg_fflags)  $(GaudiUtils_fflags)  $(GaudiObjDesc_fflags)  $(DAQEvent_fflags)  $(XmlTools_fflags)  $(GaudiKernel_fflags)  $(GaudiPluginService_fflags)  $(VectorClass_fflags)  $(GaudiPolicy_fflags)  $(Reflex_fflags)  $(ROOT_fflags)  $(Boost_fflags)  $(pyanalysis_fflags)  $(pytools_fflags)  $(Python_fflags)  $(xrootd_fflags)  $(tbb_fflags)  $(GSL_fflags)  $(vdt_fflags)  $(eigen_fflags)  $(XercesC_fflags)  $(CLHEP_fflags)  $(lapack_fflags)  $(blas_fflags)  $(mysql_fflags)  $(LCG_Settings_fflags)  $(LCG_Configuration_fflags)  $(LCG_Platforms_fflags) 
use_pp_fflags=  $(PrKernel_pp_fflags)  $(TfKernel_pp_fflags)  $(RecEvent_pp_fflags)  $(EventBase_pp_fflags)  $(OTDAQ_pp_fflags)  $(DigiEvent_pp_fflags)  $(TrackEvent_pp_fflags)  $(OTDet_pp_fflags)  $(STDet_pp_fflags)  $(VeloDet_pp_fflags)  $(DAQKernel_pp_fflags)  $(LHCbKernel_pp_fflags)  $(PartProp_pp_fflags)  $(DetDescCnv_pp_fflags)  $(DetDesc_pp_fflags)  $(LHCbMath_pp_fflags)  $(GaudiGSL_pp_fflags)  $(GaudiAlg_pp_fflags)  $(GaudiUtils_pp_fflags)  $(GaudiObjDesc_pp_fflags)  $(DAQEvent_pp_fflags)  $(XmlTools_pp_fflags)  $(GaudiKernel_pp_fflags)  $(GaudiPluginService_pp_fflags)  $(VectorClass_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(Reflex_pp_fflags)  $(ROOT_pp_fflags)  $(Boost_pp_fflags)  $(pyanalysis_pp_fflags)  $(pytools_pp_fflags)  $(Python_pp_fflags)  $(xrootd_pp_fflags)  $(tbb_pp_fflags)  $(GSL_pp_fflags)  $(vdt_pp_fflags)  $(eigen_pp_fflags)  $(XercesC_pp_fflags)  $(CLHEP_pp_fflags)  $(lapack_pp_fflags)  $(blas_pp_fflags)  $(mysql_pp_fflags)  $(LCG_Settings_pp_fflags)  $(LCG_Configuration_pp_fflags)  $(LCG_Platforms_pp_fflags) 
use_libraries= $(TfKernel_libraries)  $(RecEvent_libraries)  $(EventBase_libraries)  $(OTDAQ_libraries)  $(DigiEvent_libraries)  $(TrackEvent_libraries)  $(OTDet_libraries)  $(STDet_libraries)  $(VeloDet_libraries)  $(DAQKernel_libraries)  $(LHCbKernel_libraries)  $(PartProp_libraries)  $(DetDescCnv_libraries)  $(DetDesc_libraries)  $(LHCbMath_libraries)  $(GaudiGSL_libraries)  $(GaudiPython_libraries)  $(GaudiAlg_libraries)  $(GaudiUtils_libraries)  $(GaudiObjDesc_libraries)  $(DAQEvent_libraries)  $(XmlTools_libraries)  $(GaudiKernel_libraries)  $(GaudiPluginService_libraries)  $(VectorClass_libraries)  $(GaudiPolicy_libraries)  $(Reflex_libraries)  $(ROOT_libraries)  $(Boost_libraries)  $(pyanalysis_libraries)  $(pytools_libraries)  $(Python_libraries)  $(tcmalloc_libraries)  $(libunwind_libraries)  $(xrootd_libraries)  $(tbb_libraries)  $(GSL_libraries)  $(vdt_libraries)  $(eigen_libraries)  $(AIDA_libraries)  $(uuid_libraries)  $(XercesC_libraries)  $(CLHEP_libraries)  $(lapack_libraries)  $(blas_libraries)  $(mysql_libraries)  $(LCG_Settings_libraries)  $(LCG_Configuration_libraries)  $(LCG_Platforms_libraries) 
fincludes= $(includes)
install_more_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
PrKernel_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
PrKernelGen_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
PrKernelDict_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
PrKernelDict_use_linkopts=  $(PrKernel_linkopts)  $(TfKernel_linkopts)  $(RecEvent_linkopts)  $(EventBase_linkopts)  $(OTDAQ_linkopts)  $(DigiEvent_linkopts)  $(TrackEvent_linkopts)  $(OTDet_linkopts)  $(STDet_linkopts)  $(VeloDet_linkopts)  $(DAQKernel_linkopts)  $(LHCbKernel_linkopts)  $(PartProp_linkopts)  $(DetDescCnv_linkopts)  $(DetDesc_linkopts)  $(LHCbMath_linkopts)  $(GaudiGSL_linkopts)  $(GaudiAlg_linkopts)  $(GaudiUtils_linkopts)  $(GaudiObjDesc_linkopts)  $(DAQEvent_linkopts)  $(XmlTools_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPluginService_linkopts)  $(VectorClass_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(pyanalysis_linkopts)  $(pytools_linkopts)  $(Python_linkopts)  $(xrootd_linkopts)  $(tbb_linkopts)  $(GSL_linkopts)  $(vdt_linkopts)  $(eigen_linkopts)  $(XercesC_linkopts)  $(CLHEP_linkopts)  $(lapack_linkopts)  $(blas_linkopts)  $(mysql_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts) 
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
CompilePython_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_run_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_summarize_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestPackage_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestProject_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_rootsys_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= install_more_includes PrKernel PrKernelGen PrKernelDict 
all_constituents= $(constituents)
constituentsclean= PrKernelDictclean PrKernelGenclean PrKernelclean install_more_includesclean 
all_constituentsclean= $(constituentsclean)
