// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/02       [394754]
Creator        : sesen
Date           : Fri Apr  8 14:49:46 2016
Host           : Linux lcgapp-slc6-physical1.cern.ch 2.6.32-573.8.1.el6.x86_64 #1 SMP Wed Nov 11 15:27:45 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/s/sesen/PrSeeding/TMVA
Training events: 143266
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "700" [Number of training cycles]
HiddenLayers: "N+2,N+1,N" [Specification of hidden layer architecture]
NeuronType: "ReLU" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
chi2                          chi2                          chi2                          chi2                                                            'D'    [0.000137808368891,24.99659729]
distx                         distx                         distx                         distx                                                           'D'    [-462.013946533,402.96496582]
dslx                          dslx                          dslx                          dslx                                                            'D'    [-1.23313307762,1.27070832253]
dsly                          dsly                          dsly                          dsly                                                            'D'    [-0.114285856485,0.123050928116]
tolx                          tolx                          tolx                          tolx                                                            'D'    [64.0000152588,10398.0771484]
toly                          toly                          toly                          toly                                                            'D'    [36.0272064209,21432.6347656]
dslope                        dslope                        dslope                        dslope                                                          'D'    [-1.23313307762,1.27070832253]
teta2-tseta2                  teta2_M_tseta2                teta2-tseta2                  teta2-tseta2                                                    'D'    [-1.2199202776,0.178935825825]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPMatching : public IClassifierReader {

 public:

   // constructor
   ReadMLPMatching( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPMatching" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "chi2", "distx", "dslx", "dsly", "tolx", "toly", "dslope", "teta2-tseta2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPMatching() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[11][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[10][11];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[9][10];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][9];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLPMatching::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 10; fWeights[2] = new double[10]; 
   fLayerSize[3] = 9; fWeights[3] = new double[9]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.228942148506633;
   fWeightMatrix0to1[1][0] = -5.66693171180179;
   fWeightMatrix0to1[2][0] = 0.321498672958909;
   fWeightMatrix0to1[3][0] = 1.35477605535935;
   fWeightMatrix0to1[4][0] = -11.6063990830805;
   fWeightMatrix0to1[5][0] = -6.9928801212194;
   fWeightMatrix0to1[6][0] = -0.556890313988473;
   fWeightMatrix0to1[7][0] = 1.3867928393797;
   fWeightMatrix0to1[8][0] = -1.03912835806226;
   fWeightMatrix0to1[9][0] = 0.282599240964541;
   fWeightMatrix0to1[0][1] = -16.4744913720113;
   fWeightMatrix0to1[1][1] = -2.41262677757463;
   fWeightMatrix0to1[2][1] = -41.0377712704114;
   fWeightMatrix0to1[3][1] = -0.501352704267996;
   fWeightMatrix0to1[4][1] = -0.558229082868054;
   fWeightMatrix0to1[5][1] = -1.03989901164208;
   fWeightMatrix0to1[6][1] = 16.4191995475357;
   fWeightMatrix0to1[7][1] = 40.8409627140188;
   fWeightMatrix0to1[8][1] = 0.474568037707024;
   fWeightMatrix0to1[9][1] = -0.215486150517565;
   fWeightMatrix0to1[0][2] = -0.592667594975647;
   fWeightMatrix0to1[1][2] = -0.532239513172629;
   fWeightMatrix0to1[2][2] = 6.87757336652956;
   fWeightMatrix0to1[3][2] = -0.126280466570475;
   fWeightMatrix0to1[4][2] = -1.29374538091887;
   fWeightMatrix0to1[5][2] = -0.00193787471660195;
   fWeightMatrix0to1[6][2] = 1.63044962374591;
   fWeightMatrix0to1[7][2] = -5.96108035685809;
   fWeightMatrix0to1[8][2] = -1.4295162440457;
   fWeightMatrix0to1[9][2] = 0.520734685421367;
   fWeightMatrix0to1[0][3] = -0.564686822946009;
   fWeightMatrix0to1[1][3] = 8.8684961330704;
   fWeightMatrix0to1[2][3] = 1.42160742784762;
   fWeightMatrix0to1[3][3] = 0.0409500241206542;
   fWeightMatrix0to1[4][3] = -0.45898353653515;
   fWeightMatrix0to1[5][3] = -7.61474685196211;
   fWeightMatrix0to1[6][3] = -0.280003468319737;
   fWeightMatrix0to1[7][3] = -1.06048519340448;
   fWeightMatrix0to1[8][3] = -0.8728733417242;
   fWeightMatrix0to1[9][3] = -0.0511990792801668;
   fWeightMatrix0to1[0][4] = 0.644520843053734;
   fWeightMatrix0to1[1][4] = 1.81597110377262;
   fWeightMatrix0to1[2][4] = -1.52998978377158;
   fWeightMatrix0to1[3][4] = 1.49257745991442;
   fWeightMatrix0to1[4][4] = -7.1522073006172;
   fWeightMatrix0to1[5][4] = 2.3238984824165;
   fWeightMatrix0to1[6][4] = 2.38180819312681;
   fWeightMatrix0to1[7][4] = -0.17603715525814;
   fWeightMatrix0to1[8][4] = 1.84010802816907;
   fWeightMatrix0to1[9][4] = 5.11577111921609;
   fWeightMatrix0to1[0][5] = -0.518569637339923;
   fWeightMatrix0to1[1][5] = 0.937551167887375;
   fWeightMatrix0to1[2][5] = -12.0420415001437;
   fWeightMatrix0to1[3][5] = 1.15778917778356;
   fWeightMatrix0to1[4][5] = 1.91895388061639;
   fWeightMatrix0to1[5][5] = 1.80878301838565;
   fWeightMatrix0to1[6][5] = -0.460985796882888;
   fWeightMatrix0to1[7][5] = -14.1389115712155;
   fWeightMatrix0to1[8][5] = 1.32480157092789;
   fWeightMatrix0to1[9][5] = -1.67731455087961;
   fWeightMatrix0to1[0][6] = -1.87605832559607;
   fWeightMatrix0to1[1][6] = 0.586928502024295;
   fWeightMatrix0to1[2][6] = 5.82112584660938;
   fWeightMatrix0to1[3][6] = 0.462143249333878;
   fWeightMatrix0to1[4][6] = 1.72000375101398;
   fWeightMatrix0to1[5][6] = -0.12859793392283;
   fWeightMatrix0to1[6][6] = 0.250641032998673;
   fWeightMatrix0to1[7][6] = -6.08918566292475;
   fWeightMatrix0to1[8][6] = 1.22844182297657;
   fWeightMatrix0to1[9][6] = -0.458402368291786;
   fWeightMatrix0to1[0][7] = -0.127481053247997;
   fWeightMatrix0to1[1][7] = -1.08391720442167;
   fWeightMatrix0to1[2][7] = -1.27484935211567;
   fWeightMatrix0to1[3][7] = 0.718659880073194;
   fWeightMatrix0to1[4][7] = -4.43879948032732;
   fWeightMatrix0to1[5][7] = 1.11044467606266;
   fWeightMatrix0to1[6][7] = -0.832026310273986;
   fWeightMatrix0to1[7][7] = -0.168571443369607;
   fWeightMatrix0to1[8][7] = 0.525806276099996;
   fWeightMatrix0to1[9][7] = 4.82341565180452;
   fWeightMatrix0to1[0][8] = 1.03572336121853;
   fWeightMatrix0to1[1][8] = -2.79609424701353;
   fWeightMatrix0to1[2][8] = -8.68616368698706;
   fWeightMatrix0to1[3][8] = -1.38350880007972;
   fWeightMatrix0to1[4][8] = -8.76072467158603;
   fWeightMatrix0to1[5][8] = -3.88606897761723;
   fWeightMatrix0to1[6][8] = 0.900241946704601;
   fWeightMatrix0to1[7][8] = -15.2931135966081;
   fWeightMatrix0to1[8][8] = -2.2087453787568;
   fWeightMatrix0to1[9][8] = 0.173363040808267;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.366602056476792;
   fWeightMatrix1to2[1][0] = -1.40293299213198;
   fWeightMatrix1to2[2][0] = 1.77904942710359;
   fWeightMatrix1to2[3][0] = -1.27958718442148;
   fWeightMatrix1to2[4][0] = -4.60309504124626;
   fWeightMatrix1to2[5][0] = -4.98952802001992;
   fWeightMatrix1to2[6][0] = 1.08405236718665;
   fWeightMatrix1to2[7][0] = -1.95374440449917;
   fWeightMatrix1to2[8][0] = -2.57749992141216;
   fWeightMatrix1to2[0][1] = 0.618026928840573;
   fWeightMatrix1to2[1][1] = -1.9452448623574;
   fWeightMatrix1to2[2][1] = -0.36613694777492;
   fWeightMatrix1to2[3][1] = 0.112968127886969;
   fWeightMatrix1to2[4][1] = -2.71537407088987;
   fWeightMatrix1to2[5][1] = -1.58764057606085;
   fWeightMatrix1to2[6][1] = -2.19727832296913;
   fWeightMatrix1to2[7][1] = -1.17768659682328;
   fWeightMatrix1to2[8][1] = -1.23482533949721;
   fWeightMatrix1to2[0][2] = -0.772908760032221;
   fWeightMatrix1to2[1][2] = 0.223463610842976;
   fWeightMatrix1to2[2][2] = -0.0865740193489476;
   fWeightMatrix1to2[3][2] = -3.36899598372103;
   fWeightMatrix1to2[4][2] = 1.40949595201261;
   fWeightMatrix1to2[5][2] = 0.725256581920615;
   fWeightMatrix1to2[6][2] = -2.47952551041086;
   fWeightMatrix1to2[7][2] = -0.0834467223845782;
   fWeightMatrix1to2[8][2] = -6.66853265115676;
   fWeightMatrix1to2[0][3] = -0.956162285673331;
   fWeightMatrix1to2[1][3] = 1.10817120444235;
   fWeightMatrix1to2[2][3] = -0.558270666681891;
   fWeightMatrix1to2[3][3] = -1.59081962203259;
   fWeightMatrix1to2[4][3] = 0.200381141155541;
   fWeightMatrix1to2[5][3] = -0.278691157677313;
   fWeightMatrix1to2[6][3] = 1.59371656899722;
   fWeightMatrix1to2[7][3] = 1.00835271294911;
   fWeightMatrix1to2[8][3] = -0.00324763955404441;
   fWeightMatrix1to2[0][4] = -0.867933079068916;
   fWeightMatrix1to2[1][4] = -0.827957193931661;
   fWeightMatrix1to2[2][4] = -0.12374737899638;
   fWeightMatrix1to2[3][4] = -2.00257530454329;
   fWeightMatrix1to2[4][4] = 0.147260514932779;
   fWeightMatrix1to2[5][4] = -1.35932129666731;
   fWeightMatrix1to2[6][4] = 2.35583379334146;
   fWeightMatrix1to2[7][4] = -0.576056376410873;
   fWeightMatrix1to2[8][4] = 0.157100008423674;
   fWeightMatrix1to2[0][5] = -0.218423496029985;
   fWeightMatrix1to2[1][5] = -0.387140340830095;
   fWeightMatrix1to2[2][5] = -0.717822972915383;
   fWeightMatrix1to2[3][5] = 1.60185778863986;
   fWeightMatrix1to2[4][5] = -1.12736689930663;
   fWeightMatrix1to2[5][5] = 1.03588047081345;
   fWeightMatrix1to2[6][5] = -4.10832245310281;
   fWeightMatrix1to2[7][5] = -0.3182970891726;
   fWeightMatrix1to2[8][5] = -1.11980789402866;
   fWeightMatrix1to2[0][6] = -2.19298280462826;
   fWeightMatrix1to2[1][6] = -1.86230018046936;
   fWeightMatrix1to2[2][6] = 1.46197612216079;
   fWeightMatrix1to2[3][6] = -3.43700394633548;
   fWeightMatrix1to2[4][6] = -1.68444744287849;
   fWeightMatrix1to2[5][6] = -1.34757689489259;
   fWeightMatrix1to2[6][6] = 0.878244808159127;
   fWeightMatrix1to2[7][6] = -1.35898550580335;
   fWeightMatrix1to2[8][6] = -3.59986131888914;
   fWeightMatrix1to2[0][7] = -0.28834757659624;
   fWeightMatrix1to2[1][7] = -3.17588420073189;
   fWeightMatrix1to2[2][7] = 0.121527639394635;
   fWeightMatrix1to2[3][7] = 1.70679719496131;
   fWeightMatrix1to2[4][7] = -5.90592889962676;
   fWeightMatrix1to2[5][7] = -2.65563719019866;
   fWeightMatrix1to2[6][7] = -2.85579708335327;
   fWeightMatrix1to2[7][7] = 0.213931945543593;
   fWeightMatrix1to2[8][7] = 1.45818916083908;
   fWeightMatrix1to2[0][8] = 0.406327730246088;
   fWeightMatrix1to2[1][8] = 0.495593788861328;
   fWeightMatrix1to2[2][8] = 1.19237518261634;
   fWeightMatrix1to2[3][8] = -0.638252027770875;
   fWeightMatrix1to2[4][8] = -0.605083839180241;
   fWeightMatrix1to2[5][8] = 0.980837574228424;
   fWeightMatrix1to2[6][8] = -0.858306780614417;
   fWeightMatrix1to2[7][8] = -0.465931697540979;
   fWeightMatrix1to2[8][8] = 1.60395555575433;
   fWeightMatrix1to2[0][9] = 1.13794889529482;
   fWeightMatrix1to2[1][9] = 2.68952455593029;
   fWeightMatrix1to2[2][9] = -1.94970679232325;
   fWeightMatrix1to2[3][9] = 2.45664974698968;
   fWeightMatrix1to2[4][9] = -1.86480407314355;
   fWeightMatrix1to2[5][9] = 0.443311543283706;
   fWeightMatrix1to2[6][9] = -0.175177735522128;
   fWeightMatrix1to2[7][9] = 3.94161117780895;
   fWeightMatrix1to2[8][9] = -2.0028988758343;
   fWeightMatrix1to2[0][10] = -0.915129398072113;
   fWeightMatrix1to2[1][10] = 6.06796288520639;
   fWeightMatrix1to2[2][10] = -0.88003453537594;
   fWeightMatrix1to2[3][10] = -1.4341322284194;
   fWeightMatrix1to2[4][10] = 1.94771937543183;
   fWeightMatrix1to2[5][10] = 2.03874698335285;
   fWeightMatrix1to2[6][10] = -6.0667824760489;
   fWeightMatrix1to2[7][10] = 5.73478528245366;
   fWeightMatrix1to2[8][10] = 2.95115116875146;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.227907264399976;
   fWeightMatrix2to3[1][0] = -1.12730997719679;
   fWeightMatrix2to3[2][0] = 0.80900810406057;
   fWeightMatrix2to3[3][0] = 1.77751313048344;
   fWeightMatrix2to3[4][0] = 1.44420535773177;
   fWeightMatrix2to3[5][0] = -0.436603608991532;
   fWeightMatrix2to3[6][0] = -0.639285856552052;
   fWeightMatrix2to3[7][0] = -1.9406109180775;
   fWeightMatrix2to3[0][1] = 0.650129453146185;
   fWeightMatrix2to3[1][1] = 1.72661325115177;
   fWeightMatrix2to3[2][1] = -1.61170312143856;
   fWeightMatrix2to3[3][1] = -0.395946627201603;
   fWeightMatrix2to3[4][1] = 0.217347701900536;
   fWeightMatrix2to3[5][1] = -1.49345261433644;
   fWeightMatrix2to3[6][1] = -0.955227979271831;
   fWeightMatrix2to3[7][1] = -2.00748102422291;
   fWeightMatrix2to3[0][2] = 1.03365374573302;
   fWeightMatrix2to3[1][2] = 0.159579476514738;
   fWeightMatrix2to3[2][2] = -0.0705494629106851;
   fWeightMatrix2to3[3][2] = -1.15076505708784;
   fWeightMatrix2to3[4][2] = 0.101685947869606;
   fWeightMatrix2to3[5][2] = 0.556823093687485;
   fWeightMatrix2to3[6][2] = -0.582502012484853;
   fWeightMatrix2to3[7][2] = 0.363566065988337;
   fWeightMatrix2to3[0][3] = -0.578412711664718;
   fWeightMatrix2to3[1][3] = -0.247451455262212;
   fWeightMatrix2to3[2][3] = 1.26526158310615;
   fWeightMatrix2to3[3][3] = 0.874864364290904;
   fWeightMatrix2to3[4][3] = 1.19147798963649;
   fWeightMatrix2to3[5][3] = 0.205361611859499;
   fWeightMatrix2to3[6][3] = -1.33973350434672;
   fWeightMatrix2to3[7][3] = 0.31057664731415;
   fWeightMatrix2to3[0][4] = 0.542716561101724;
   fWeightMatrix2to3[1][4] = -1.50804572891501;
   fWeightMatrix2to3[2][4] = 0.0481007613743415;
   fWeightMatrix2to3[3][4] = 0.534880091364774;
   fWeightMatrix2to3[4][4] = -1.19610425749398;
   fWeightMatrix2to3[5][4] = -0.85849404843899;
   fWeightMatrix2to3[6][4] = 0.389700840262066;
   fWeightMatrix2to3[7][4] = -1.96421932499571;
   fWeightMatrix2to3[0][5] = -0.988609862398247;
   fWeightMatrix2to3[1][5] = 1.08075290124044;
   fWeightMatrix2to3[2][5] = -0.0920215841821529;
   fWeightMatrix2to3[3][5] = 1.22361021177275;
   fWeightMatrix2to3[4][5] = -1.2381760274095;
   fWeightMatrix2to3[5][5] = 0.854058073591683;
   fWeightMatrix2to3[6][5] = -1.04974840268102;
   fWeightMatrix2to3[7][5] = 0.595149678282716;
   fWeightMatrix2to3[0][6] = -1.04637172983447;
   fWeightMatrix2to3[1][6] = -2.10133584621978;
   fWeightMatrix2to3[2][6] = -1.38427998474515;
   fWeightMatrix2to3[3][6] = -3.35055858656748;
   fWeightMatrix2to3[4][6] = -0.483467530805464;
   fWeightMatrix2to3[5][6] = -2.08576499896962;
   fWeightMatrix2to3[6][6] = 0.045890247735632;
   fWeightMatrix2to3[7][6] = -2.17223604729405;
   fWeightMatrix2to3[0][7] = 0.960458350859598;
   fWeightMatrix2to3[1][7] = -1.92857562969165;
   fWeightMatrix2to3[2][7] = -1.25673323229057;
   fWeightMatrix2to3[3][7] = -0.870863694783869;
   fWeightMatrix2to3[4][7] = -1.60171453482215;
   fWeightMatrix2to3[5][7] = 0.36824310641629;
   fWeightMatrix2to3[6][7] = -1.13038019641859;
   fWeightMatrix2to3[7][7] = 0.947701974977217;
   fWeightMatrix2to3[0][8] = 0.694930604444209;
   fWeightMatrix2to3[1][8] = 1.36582559499907;
   fWeightMatrix2to3[2][8] = -0.227552380231235;
   fWeightMatrix2to3[3][8] = 0.422923462630487;
   fWeightMatrix2to3[4][8] = -0.752642728141954;
   fWeightMatrix2to3[5][8] = -1.46746909807383;
   fWeightMatrix2to3[6][8] = -0.175002912904369;
   fWeightMatrix2to3[7][8] = -1.2278928636358;
   fWeightMatrix2to3[0][9] = -0.835840824147251;
   fWeightMatrix2to3[1][9] = -1.94723823868561;
   fWeightMatrix2to3[2][9] = -2.06942369581294;
   fWeightMatrix2to3[3][9] = 0.840480081607127;
   fWeightMatrix2to3[4][9] = -0.709172555997029;
   fWeightMatrix2to3[5][9] = -4.02210706575343;
   fWeightMatrix2to3[6][9] = 3.38789853695522;
   fWeightMatrix2to3[7][9] = -1.80187547754776;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -0.950435952421046;
   fWeightMatrix3to4[0][1] = -0.34133803490544;
   fWeightMatrix3to4[0][2] = 0.72022453404393;
   fWeightMatrix3to4[0][3] = -0.282384161763477;
   fWeightMatrix3to4[0][4] = -0.739232210151297;
   fWeightMatrix3to4[0][5] = 1.24755873817813;
   fWeightMatrix3to4[0][6] = -0.580474513006358;
   fWeightMatrix3to4[0][7] = -0.355508088327958;
   fWeightMatrix3to4[0][8] = 3.46419350898425;
}

inline double ReadMLPMatching::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLPMatching::ActivationFnc(double x) const {
   // rectified linear unit
   return x>0 ? x : 0; 
}
double ReadMLPMatching::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLPMatching::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLPMatching::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPMatching::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.000137808368891;
   fMax_1[0][0] = 24.9424877167;
   fMin_1[1][0] = 0.000473272637464;
   fMax_1[1][0] = 24.99659729;
   fMin_1[2][0] = 0.000137808368891;
   fMax_1[2][0] = 24.99659729;
   fMin_1[0][1] = -269.152130127;
   fMax_1[0][1] = 242.124420166;
   fMin_1[1][1] = -462.013946533;
   fMax_1[1][1] = 402.96496582;
   fMin_1[2][1] = -462.013946533;
   fMax_1[2][1] = 402.96496582;
   fMin_1[0][2] = -1.23313307762;
   fMax_1[0][2] = 1.27070832253;
   fMin_1[1][2] = -1.21195542812;
   fMax_1[1][2] = 1.27016246319;
   fMin_1[2][2] = -1.23313307762;
   fMax_1[2][2] = 1.27070832253;
   fMin_1[0][3] = -0.103838652372;
   fMax_1[0][3] = 0.111917793751;
   fMin_1[1][3] = -0.114285856485;
   fMax_1[1][3] = 0.123050928116;
   fMin_1[2][3] = -0.114285856485;
   fMax_1[2][3] = 0.123050928116;
   fMin_1[0][4] = 64.0242233276;
   fMax_1[0][4] = 10398.0771484;
   fMin_1[1][4] = 64.0000152588;
   fMax_1[1][4] = 10389.2011719;
   fMin_1[2][4] = 64.0000152588;
   fMax_1[2][4] = 10398.0771484;
   fMin_1[0][5] = 36.5364151001;
   fMax_1[0][5] = 19159.296875;
   fMin_1[1][5] = 36.0272064209;
   fMax_1[1][5] = 21432.6347656;
   fMin_1[2][5] = 36.0272064209;
   fMax_1[2][5] = 21432.6347656;
   fMin_1[0][6] = -1.23313307762;
   fMax_1[0][6] = 1.27070832253;
   fMin_1[1][6] = -1.21195542812;
   fMax_1[1][6] = 1.27016246319;
   fMin_1[2][6] = -1.23313307762;
   fMax_1[2][6] = 1.27070832253;
   fMin_1[0][7] = -1.20412373543;
   fMax_1[0][7] = 0.178935825825;
   fMin_1[1][7] = -1.2199202776;
   fMax_1[1][7] = 0.171216070652;
   fMin_1[2][7] = -1.2199202776;
   fMax_1[2][7] = 0.178935825825;
}

//_______________________________________________________________________
inline void ReadMLPMatching::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPMatching::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPMatching::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
